# Generated by Django 3.2.13 on 2022-06-20 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
                ('type', models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend'), ('iOS', 'iOS'), ('android', 'android')], max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('contributors', models.ManyToManyField(related_name='contributing_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
